version: '3.7'

services:
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
            - MONGO_INITDB_DATABASE=test
        ports:
            - 27021:27017
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ConnectionStrings__mongoDb=mongodb://root:example@mongodb/test?authSource=admin
            - ASPNETCORE_Logging__LogLevel__Default=Debug
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - mongodb
        ports:
            - 8083:80
